#!/usr/bin/env node
// Bumps the patch version in package.json and regenerates lib/version.ts.
// Run before every push (see CLAUDE.md hard rules) - no CI in this timebox,
// so this is a manual-but-required step rather than a git hook.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const pkgPath = path.join(root, "package.json");
const versionFilePath = path.join(root, "lib", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const [major, minor, patch] = pkg.version.split(".").map(Number);
const nextVersion = `${major}.${minor}.${patch + 1}`;

pkg.version = nextVersion;
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

const versionFileContent = `// Auto-generated by scripts/bump-version.mjs - do not edit by hand.
export const APP_VERSION = "${nextVersion}";
export const BUILD_DATE = "${new Date().toISOString()}";
`;
writeFileSync(versionFilePath, versionFileContent);

console.log(`Bumped version: ${pkg.version} -> ${nextVersion}`);
